version: '3.8'

services:
  postgres:
    container_name: nexu_postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nexu
      POSTGRES_PASSWORD: nexu
      POSTGRES_DB: nexu_dev
    volumes:
      - ./data/pg:/data/postgres